package com.lakshya.sms.model;

/** A student (one row of the "students" table, plus the course name from the JOIN). */
public class Student {
    private int id;
    private String name;
    private String email;
    private int age;
    private int courseId;
    private String courseName;   // filled only when data is read using a JOIN

    /** Used when adding a new student (id is generated by the database). */
    public Student(String name, String email, int age, int courseId) {
        this.name = name;
        this.email = email;
        this.age = age;
        this.courseId = courseId;
    }

    /** Used when reading a student from the database. */
    public Student(int id, String name, String email, int age, int courseId, String courseName) {
        this(name, email, age, courseId);
        this.id = id;
        this.courseName = courseName;
    }

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }
    public int getCourseId() { return courseId; }
    public void setCourseId(int courseId) { this.courseId = courseId; }
    public String getCourseName() { return courseName; }
    public void setCourseName(String courseName) { this.courseName = courseName; }
}
